//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Duty()
        {
            this.Users = new HashSet<User>();
        }
    
        public int DutyId { get; set; }
        public string DutyName { get; set; }
        public string Description { get; set; }
        public System.DateTime DutyDueDate { get; set; }
        public Nullable<System.DateTime> DutyCompletion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
